-- ============================================================
-- Messenger MVP: схема Supabase
-- Запускайте этот файл ОДИН РАЗ в Supabase -> SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- Profiles ----------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Автоматически создаём профиль после регистрации.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      split_part(coalesce(new.email, 'user'), '@', 1)
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ---------- Chats ----------

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  type text not null default 'direct' check (type in ('direct', 'group')),
  created_at timestamptz not null default now()
);

create table if not exists public.chat_members (
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (chat_id, user_id)
);

alter table public.chats enable row level security;
alter table public.chat_members enable row level security;

-- Для MVP клиент не читает chat_members напрямую.
-- Доступ к созданию/поиску личного чата выполняет функция start_direct_chat().

-- ---------- Messages ----------

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id uuid not null references public.chats(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists messages_chat_created_idx
on public.messages (chat_id, created_at);

alter table public.messages enable row level security;

drop policy if exists "messages_select_if_member" on public.messages;
create policy "messages_select_if_member"
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = messages.chat_id
      and cm.user_id = auth.uid()
  )
);

drop policy if exists "messages_insert_if_member" on public.messages;
create policy "messages_insert_if_member"
on public.messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = messages.chat_id
      and cm.user_id = auth.uid()
  )
);

-- ---------- RPC: открыть или создать личный чат ----------

create or replace function public.start_direct_chat(p_other_user uuid)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_me uuid := auth.uid();
  v_chat_id uuid;
begin
  if v_me is null then
    raise exception 'Not authenticated';
  end if;

  if p_other_user is null or p_other_user = v_me then
    raise exception 'Invalid other user';
  end if;

  if not exists (select 1 from auth.users where id = p_other_user) then
    raise exception 'User not found';
  end if;

  -- Ищем direct-чат, где ровно два участника: текущий и выбранный пользователь.
  select c.id
  into v_chat_id
  from public.chats c
  where c.type = 'direct'
    and exists (
      select 1
      from public.chat_members cm
      where cm.chat_id = c.id and cm.user_id = v_me
    )
    and exists (
      select 1
      from public.chat_members cm
      where cm.chat_id = c.id and cm.user_id = p_other_user
    )
    and (
      select count(*)
      from public.chat_members cm
      where cm.chat_id = c.id
    ) = 2
  order by c.created_at
  limit 1;

  if v_chat_id is not null then
    return v_chat_id;
  end if;

  insert into public.chats (type)
  values ('direct')
  returning id into v_chat_id;

  insert into public.chat_members (chat_id, user_id)
  values
    (v_chat_id, v_me),
    (v_chat_id, p_other_user);

  return v_chat_id;
end;
$$;

revoke all on function public.start_direct_chat(uuid) from public;
grant execute on function public.start_direct_chat(uuid) to authenticated;

-- ---------- Realtime ----------

-- Postgres Changes требует публикацию таблицы.
-- Блок ниже безопасно проверяет, добавлена ли таблица messages.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
