-- ============================================================
-- Messenger MVP: схема Supabase
-- Запускайте этот файл ОДИН РАЗ в Supabase -> SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

-- ---------- Profiles ----------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9_]{3,32}$'),
  display_name text not null,
  avatar_url text,
  bio text not null default '',
  status text not null default 'offline',
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_display_name_idx
on public.profiles (display_name);

create unique index if not exists profiles_username_lower_idx
on public.profiles (lower(username));

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles
for select
to authenticated
using ((select auth.uid()) is not null);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

revoke all on table public.profiles from anon;
grant select, update on table public.profiles to authenticated;

-- Автоматически создаём профиль после регистрации.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  base_username text;
  generated_username text;
begin
  base_username := regexp_replace(
    lower(
      coalesce(
        nullif(new.raw_user_meta_data ->> 'display_name', ''),
        split_part(coalesce(new.email, 'user'), '@', 1),
        'user'
      )
    ),
    '[^a-z0-9_]+',
    '',
    'g'
  );

  if char_length(base_username) < 3 then
    base_username := 'user';
  end if;

  generated_username := left(base_username, 23) || '_' ||
    replace(substring(new.id::text from 1 for 8), '-', '');

  insert into public.profiles (
    id,
    username,
    display_name,
    bio,
    status,
    created_at,
    updated_at
  )
  values (
    new.id,
    generated_username,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      split_part(coalesce(new.email, 'user'), '@', 1)
    ),
    '',
    'offline',
    now(),
    now()
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

revoke all on function private.handle_new_user()
from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function private.set_profile_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_profile_updated_at()
from public, anon, authenticated;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_profile_updated_at();

-- ---------- Chats ----------

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  type text not null default 'direct' check (type in ('direct', 'group')),
  created_at timestamptz not null default now()
);

create table if not exists public.chat_members (
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (chat_id, user_id)
);

create index if not exists chat_members_user_id_idx
on public.chat_members (user_id);

alter table public.chats enable row level security;
alter table public.chat_members enable row level security;

-- Для MVP клиент не читает chat_members напрямую.
-- Доступ к созданию/поиску личного чата выполняет функция start_direct_chat().

-- ---------- Messages ----------

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id uuid not null references public.chats(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists messages_chat_created_idx
on public.messages (chat_id, created_at);

create index if not exists messages_sender_id_idx
on public.messages (sender_id);

alter table public.messages enable row level security;

drop policy if exists "messages_select_if_member" on public.messages;
create policy "messages_select_if_member"
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = messages.chat_id
      and cm.user_id = (select auth.uid())
  )
);

drop policy if exists "messages_insert_if_member" on public.messages;
create policy "messages_insert_if_member"
on public.messages
for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = messages.chat_id
      and cm.user_id = (select auth.uid())
  )
);

-- ---------- RPC: открыть или создать личный чат ----------

create or replace function public.start_direct_chat(p_other_user uuid)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_me uuid := auth.uid();
  v_chat_id uuid;
begin
  if v_me is null then
    raise exception 'Not authenticated';
  end if;

  if p_other_user is null or p_other_user = v_me then
    raise exception 'Invalid other user';
  end if;

  if not exists (select 1 from auth.users where id = p_other_user) then
    raise exception 'User not found';
  end if;

  -- Ищем direct-чат, где ровно два участника: текущий и выбранный пользователь.
  select c.id
  into v_chat_id
  from public.chats c
  where c.type = 'direct'
    and exists (
      select 1
      from public.chat_members cm
      where cm.chat_id = c.id and cm.user_id = v_me
    )
    and exists (
      select 1
      from public.chat_members cm
      where cm.chat_id = c.id and cm.user_id = p_other_user
    )
    and (
      select count(*)
      from public.chat_members cm
      where cm.chat_id = c.id
    ) = 2
  order by c.created_at
  limit 1;

  if v_chat_id is not null then
    return v_chat_id;
  end if;

  insert into public.chats (type)
  values ('direct')
  returning id into v_chat_id;

  insert into public.chat_members (chat_id, user_id)
  values
    (v_chat_id, v_me),
    (v_chat_id, p_other_user);

  return v_chat_id;
end;
$$;

revoke all on function public.start_direct_chat(uuid) from public, anon;
grant execute on function public.start_direct_chat(uuid) to authenticated;

-- ---------- Realtime ----------

-- Postgres Changes требует публикацию таблицы.
-- Блок ниже безопасно проверяет, добавлена ли таблица messages.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
