-- Fix chat membership checks, add private message attachments and personal contact tasks.

-- Signed-in users may only inspect their own membership row. This makes the
-- messages RLS membership subquery work without exposing other chat members.
drop policy if exists "chat_members_select_self" on public.chat_members;
create policy "chat_members_select_self"
on public.chat_members
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "chats_select_if_member" on public.chats;
create policy "chats_select_if_member"
on public.chats
for select
to authenticated
using (
  exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = chats.id
      and cm.user_id = (select auth.uid())
  )
);

-- Replace Supabase's broad default table grants with the minimum used by the client.
revoke all on table public.chats from anon, authenticated;
revoke all on table public.chat_members from anon, authenticated;
revoke all on table public.messages from anon, authenticated;
grant select on table public.chats to authenticated;
grant select on table public.chat_members to authenticated;
grant select, insert on table public.messages to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;

alter table public.messages
  add column if not exists attachment_path text,
  add column if not exists attachment_name text,
  add column if not exists attachment_type text,
  add column if not exists attachment_size bigint;

alter table public.messages
  alter column body set default '',
  alter column body drop not null;

alter table public.messages
  drop constraint if exists messages_body_check;

alter table public.messages
  drop constraint if exists messages_content_check;

alter table public.messages
  add constraint messages_content_check check (
    char_length(coalesce(body, '')) <= 4000
    and (
      char_length(trim(coalesce(body, ''))) > 0
      or attachment_path is not null
    )
    and (
      attachment_path is null
      or (
        attachment_name is not null
        and attachment_type is not null
        and attachment_size between 1 and 20971520
      )
    )
  );

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'message-attachments',
  'message-attachments',
  false,
  20971520,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'application/pdf',
    'text/plain',
    'application/zip',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "message_attachments_insert_member" on storage.objects;
create policy "message_attachments_insert_member"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'message-attachments'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and exists (
    select 1
    from public.chat_members cm
    where cm.user_id = (select auth.uid())
      and cm.chat_id = ((storage.foldername(name))[2])::uuid
  )
);

drop policy if exists "message_attachments_select_member" on storage.objects;
create policy "message_attachments_select_member"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'message-attachments'
  and exists (
    select 1
    from public.chat_members cm
    where cm.user_id = (select auth.uid())
      and cm.chat_id = ((storage.foldername(name))[2])::uuid
  )
);

drop policy if exists "message_attachments_delete_owner" on storage.objects;
create policy "message_attachments_delete_owner"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'message-attachments'
  and owner_id = (select auth.uid())::text
);

-- Calendar tasks belong to one owner and are assigned to one of their contacts.
create table if not exists public.calendar_tasks (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  contact_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  notes text not null default '',
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'planned',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_tasks_title_check check (char_length(trim(title)) between 1 and 200),
  constraint calendar_tasks_notes_check check (char_length(notes) <= 2000),
  constraint calendar_tasks_status_check check (status in ('planned', 'done')),
  constraint calendar_tasks_time_check check (ends_at is null or ends_at > starts_at)
);

create index if not exists calendar_tasks_owner_starts_idx
on public.calendar_tasks (owner_id, starts_at);

create index if not exists calendar_tasks_contact_id_idx
on public.calendar_tasks (contact_id);

alter table public.calendar_tasks enable row level security;

drop policy if exists "calendar_tasks_select_own" on public.calendar_tasks;
create policy "calendar_tasks_select_own"
on public.calendar_tasks
for select
to authenticated
using (owner_id = (select auth.uid()));

drop policy if exists "calendar_tasks_insert_own_contact" on public.calendar_tasks;
create policy "calendar_tasks_insert_own_contact"
on public.calendar_tasks
for insert
to authenticated
with check (
  owner_id = (select auth.uid())
  and (
    contact_id = (select auth.uid())
    or exists (
      select 1
      from public.contacts c
      where c.owner_id = (select auth.uid())
        and c.contact_id = calendar_tasks.contact_id
    )
  )
);

drop policy if exists "calendar_tasks_update_own_contact" on public.calendar_tasks;
create policy "calendar_tasks_update_own_contact"
on public.calendar_tasks
for update
to authenticated
using (owner_id = (select auth.uid()))
with check (
  owner_id = (select auth.uid())
  and (
    contact_id = (select auth.uid())
    or exists (
      select 1
      from public.contacts c
      where c.owner_id = (select auth.uid())
        and c.contact_id = calendar_tasks.contact_id
    )
  )
);

drop policy if exists "calendar_tasks_delete_own" on public.calendar_tasks;
create policy "calendar_tasks_delete_own"
on public.calendar_tasks
for delete
to authenticated
using (owner_id = (select auth.uid()));

revoke all on table public.calendar_tasks from anon, authenticated;
grant select, insert, update, delete on table public.calendar_tasks to authenticated;
grant usage, select on sequence public.calendar_tasks_id_seq to authenticated;

create or replace function private.set_calendar_task_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_calendar_task_updated_at()
from public, anon, authenticated;

drop trigger if exists calendar_tasks_set_updated_at on public.calendar_tasks;
create trigger calendar_tasks_set_updated_at
before update on public.calendar_tasks
for each row execute function private.set_calendar_task_updated_at();
